service: scraper-lambda

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs8.10
  region: eu-west-3
  stage: dev

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: "yarn"

  serverless-offline:
    location: .webpack/service

functions:
  give-me:
    handler: functions/handler.scrap
    timeout: 20
    memorySize: 1536
    events:
      - http:
          path: scrap
          method: post
          cors: true
